### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by edmondklai** [knocklabs/react-notification-feed#24]
`"@knocklabs/react-notification-feed": "^0.8.1"`

Putting in the react snippet `KnockFeedProvider` from doc generate the following errors. 
![Screen Shot 2022-11-04 at 4 15 37 PM](https://user-images.githubusercontent.com/23513440/200076044-f1363f76-45b9-405d-8b79-123d93663597.png)

**Comment by edmondklai** [comment]
NextJS issue on my end.

**Comment by enaluz** [comment]
I'm running into this problem too (Remix). Did you find a fix for this @edmondklai?

**Comment by cjbell** [comment]
@enaluz The issue here is that the `Feed` expects to be client-side rendered and not server-side rendered, which is why you're seeing the `self is undefined` issue. So here you'll need to find a way to force this to render on the client only. Not sure on the remix specific solution here, but typically it looks something like setting some state that only gets triggered on component mount and then using that to render.

**Comment by edmondklai** [comment]
Yea, it was a server side vs client side rendering issue. For NextJS I am doing something like this

```typescript
import dynamic from "next/dynamic";

const KnockFeedProvider = dynamic(
  () => import("../../components/notifications/KnockFeedProvider"),
  {
    ssr: false,
  }
);

 <KnockFeedProvider userId={userId} />
```

```typescript
import {
  KnockFeedProvider,
  NotificationIconButton,
  NotificationFeedPopover,
} from "@knocklabs/react-notification-feed";
import "@knocklabs/react-notification-feed/dist/index.css";
import { useRef, useState } from "react";

const KnockFeedProviderWrapper = ({ userId }: { userId: string }) => {
  const [isVisible, setIsVisible] = useState(false);
  const notifButtonRef = useRef(null);

  return (
    <KnockFeedProvider
      apiKey={process.env.NEXT_PUBLIC_KNOCK_PUBLIC_API_KEY as string}
      feedId={process.env.NEXT_PUBLIC_KNOCK_FEED_CHANNEL_ID as string}
      userId={userId}
    >
      <>
        <NotificationIconButton
          ref={notifButtonRef}
          onClick={(e) => setIsVisible(!isVisible)}
        />
        <NotificationFeedPopover
          buttonRef={notifButtonRef}
          isVisible={isVisible}
          onClose={() => setIsVisible(false)}
        />
      </>
    </KnockFeedProvider>
  );
};

export default KnockFeedProviderWrapper;
```
