### ISSUE TITLE
More customisation over Feed UI composition without needing to reimplement

### ISSUE THREAD

**Issue by TimNZ** [knocklabs/react-notification-feed#33]
Lazy feature request: the ability to inject custom components into the React Notification Feed component.

I want to add a 'Configure Notification Settings' button/icon somewhere in the popover that takes people to custom notification settings page.

If I could inject custom content above and below the header via 'renderAboveHeader' and 'renderBelowHeader' type props that accept a ReactNode would be a huge time saver over making a custom Feed component to achieve this.

![image](https://github.com/knocklabs/react-notification-feed/assets/1051701/53612861-5beb-4256-9c3c-ce61ba8c9179)

**Comment by connorlindsey** [comment]
Thanks for the feature request. This is something we've discussed as a team and may include in the future but will not currently be prioritizing it. As we're migrating our React components over to a [new package](https://github.com/knocklabs/javascript/tree/main/packages/react), I'm going to close this for the time being.
