### ISSUE TITLE
Bug: KnockI18nProvider and useTranslations hook are not available

### ISSUE THREAD

**Issue by witoldmetel** [knocklabs/react-notification-feed#44]
```
"@knocklabs/client": "0.8.13",
 "@knocklabs/node": "0.4.24",
"@knocklabs/react-notification-feed": "0.8.12",
```

`KnockI18nProvider` and `useTranslations` hook are not available for version 0.8.12

**Comment by connorlindsey** [comment]
Hi @witoldmetel, looks like there was an issue with those exports that was fixed as of version `0.8.13`. Please consider upgrading to a later version of the package if you're using translations.
