### ISSUE TITLE
Bug: Translations for dates don't work

### ISSUE THREAD

**Issue by witoldmetel** [knocklabs/react-notification-feed#45]
```
dateFnsLocale: (): DateFnLocale => {
      return locale in dateFnsLocales
        ? dateFnsLocales[locale]
        : dateFnsLocales.enUS;
    }

  ```
    
   In `useTranslations` hook,  date-fns `locale` accept different format. For example for polish:
   I sent locale: `pl-PL` but it doesn't translate dates in `NotificationCell`.  If I pass `pl` it works.

```
  <span className="rnf-notification-cell__timestamp">
            {formatTimestamp(item.inserted_at, { locale: dateFnsLocale() })}
          </span>
```

**Comment by veerbal1** [comment]
Can you share your NotificationCell Code?

**Comment by connorlindsey** [comment]
Hi @witoldmetel, the locale strings are defined by date-fns and can be found here https://github.com/date-fns/date-fns/tree/main/src/locale. I'm going to close this as it is working as expected.
