### ISSUE TITLE
How to implement multiple action buttons?

### ISSUE THREAD

**Issue by danilofuchs** [knocklabs/react-notification-feed#51]
This is the desired notification:

![image](https://github.com/knocklabs/react-notification-feed/assets/17657014/09149887-7092-4f87-9b65-6971b4cdf0a6)

Knock's landing page has something like this:

![image](https://github.com/knocklabs/react-notification-feed/assets/17657014/ee8d1dc2-a68f-4505-9e98-84c1875734b2)

How can we achieve this?

**Comment by JEverhart383** [comment]
Hi @danilofuchs thanks for the question. I think these might be the docs you are looking for: https://docs.knock.app/in-app-ui/react/feed#adding-inline-actions

Using the `renderItem` prop you can override the default behavior of the `NotificationCell` component and pass in additional buttons with your own click handlers.

**Comment by danilofuchs** [comment]
Thanks!
